# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: SelfHostedLocal  # your local agent

variables:
- group: SaaS_Billing_System_Variables  # contains DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME

steps:
- checkout: self  # ensures repo files are on local agent

- powershell: |
    $sqlFile = "$(Build.SourcesDirectory)\create_tables.sql"
    Write-Host "Running SQL script: $sqlFile"
    & "C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe" `
        -h $(DB_HOST) `
        -P $(DB_PORT) `
        -u $(DB_USER) `
        -p$(DB_PASSWORD) `
        $(DB_NAME) `
        < $sqlFile
  displayName: 'Run SQL script on local MySQL'



